# Generated by Django 4.0 on 2022-01-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searched',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='searched',
            name='latest_time_stamp',
        ),
    ]
