# Generated by Django 4.0 on 2022-01-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_searched_hits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searched',
            old_name='first_time_stamp',
            new_name='time_stamp',
        ),
    ]
